import React from "react";
import Image from "next/image";
import logo from "../../../public/assets/logo/navbar-logo.svg";
import instagram from "../../../public/assets/socials/instagram.svg";
import whatsapp from "../../../public/assets/socials/whatsapp.svg";
import telegram from "../../../public/assets/socials/telegram.svg";
import guracad from "../../../public/assets/downloads/guracad.svg";
import android from "../../../public/assets/downloads/android.svg";
import whatsappnow from "../../../public/assets/downloads/whatsappnow.svg";
import upi from "../../../public/assets/footer/upi.svg";
import bank from "../../../public/assets/footer/bank.svg";
import begamble from "../../../public/assets/footer/begamble.svg";
import gamblingcommission from "../../../public/assets/footer/gamblingcomission.svg";
import ecogra from "../../../public/assets/footer/ecogra.svg";
import mga from "../../../public/assets/footer/mga.svg";

const MobileFooter = () => {
  return (
    <div className='w-full p-3 space-y-5'>
      <div className='flex w-full justify-between'>
        <Image
          className='h-8 w-20'
          src={logo}
          alt=''
          height={100}
          width={100}
        ></Image>
        <div className='flex space-x-1'>
          <Image
            className='h-8 w-8'
            src={instagram}
            alt=''
            height={100}
            width={100}
          ></Image>
          <Image
            className='h-8 w-8'
            src={telegram}
            alt=''
            height={100}
            width={100}
          ></Image>
          <Image
            className='h-8 w-8'
            src={whatsapp}
            alt=''
            height={100}
            width={100}
          ></Image>
        </div>
      </div>
      <div className='flex justify-between pt-2'>
        <Image
          className='h-8 w-auto'
          src={guracad}
          alt=''
          height={100}
          width={100}
        ></Image>
        <Image
          className='h-8 w-auto'
          src={android}
          alt=''
          height={100}
          width={100}
        ></Image>
        <Image
          className='h-8 w-auto'
          src={whatsappnow}
          alt=''
          height={100}
          width={100}
        ></Image>
      </div>
      <p className='text-xs text-darktext'>
        LOTUS 365 casino is a limited liability company incorporated under the
        laws of Curacao Players are requested not to contact any unreliable
        sources for LOTUS 365 casino accounts as this is an online site and they
        can only register independently without any agents. Only deposit through
        the account details generated by the system or provided by our official
        support team.
      </p>
      <div className='flex justify-between'>
        <Image
          className='h-8 w-auto'
          src={upi}
          alt=''
          height={100}
          width={100}
        ></Image>
        <Image
          className='h-8 w-auto'
          src={bank}
          alt=''
          height={100}
          width={100}
        ></Image>
        <Image
          className='h-8 w-auto'
          src={begamble}
          alt=''
          height={100}
          width={100}
        ></Image>
      </div>
      <div className='flex justify-between'>
        <Image
          className='h-8 w-auto'
          src={gamblingcommission}
          alt=''
          height={100}
          width={100}
        ></Image>
        <Image
          className='h-8 w-auto'
          src={ecogra}
          alt=''
          height={100}
          width={100}
        ></Image>
        <Image
          className='h-8 w-auto'
          src={mga}
          alt=''
          height={100}
          width={100}
        ></Image>
      </div>
      <div className='text-center text-darktext text-sm'>
        All Rights Reserved &copy; lotus365casino
      </div>
    </div>
  );
};

export default MobileFooter;
